const UserList = [
  {
    id: 1,
    name: "John Doe",
    username: "johnd",
    age: 25,
    nationality: "American",
  },
  {
    id: 2,
    name: "Jane Smith",
    username: "janes",
    age: 30,
    nationality: "British",
  },
  {
    id: 3,
    name: "Akira Tanaka",
    username: "akirat",
    age: 28,
    nationality: "Japanese",
  },
  {
    id: 4,
    name: "Maria Gonzalez",
    username: "mariag",
    age: 27,
    nationality: "Mexican",
  },
  {
    id: 5,
    name: "Liam O'Brien",
    username: "liamo",
    age: 32,
    nationality: "Irish",
  },
  {
    id: 6,
    name: "Emma Brown",
    username: "emmab",
    age: 22,
    nationality: "Australian",
  },
  {
    id: 7,
    name: "Chen Wei",
    username: "chenw",
    age: 29,
    nationality: "Chinese",
  },
  {
    id: 8,
    name: "Olivia Davis",
    username: "oliviad",
    age: 26,
    nationality: "Canadian",
  },
  {
    id: 9,
    name: "Raj Patel",
    username: "rajp",
    age: 31,
    nationality: "Indian",
  },
  {
    id: 10,
    name: "Sophia Martinez",
    username: "sophiam",
    age: 24,
    nationality: "Spanish",
  },
  {
    id: 11,
    name: "Noah Wilson",
    username: "noahw",
    age: 27,
    nationality: "New Zealander",
  },
  {
    id: 12,
    name: "Isabella Rossi",
    username: "isabellar",
    age: 29,
    nationality: "Italian",
  },
  {
    id: 13,
    name: "William Kim",
    username: "williamk",
    age: 23,
    nationality: "South Korean",
  },
  {
    id: 14,
    name: "Emily Lopez",
    username: "emilyl",
    age: 28,
    nationality: "Colombian",
  },
  {
    id: 15,
    name: "Ethan Johnson",
    username: "ethanj",
    age: 30,
    nationality: "South African",
  },
  {
    id: 16,
    name: "Chloe White",
    username: "chloew",
    age: 21,
    nationality: "American",
  },
  {
    id: 17,
    name: "Aarav Gupta",
    username: "aaravg",
    age: 26,
    nationality: "Indian",
  },
  {
    id: 18,
    name: "Zara Khan",
    username: "zarak",
    age: 27,
    nationality: "Pakistani",
  },
  {
    id: 19,
    name: "Lucas Hernandez",
    username: "lucash",
    age: 25,
    nationality: "Argentinian",
  },
  {
    id: 20,
    name: "Mia Wagner",
    username: "miaw",
    age: 24,
    nationality: "German",
  },
];

module.exports = { UserList };